!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = wave_serverV

OBJS = \
	$(APP).obj \
	compare.obj \
	index.obj \
	index_util.obj \
	serve_trace.obj \
	server_thread.obj \
	tb_packet_db.obj

EW_LIBS = \
	/LIBPATH:$L \
	mem_circ_queue.obj \
	socket_ew.obj \
	socket_ew_common.obj \
	sqlite3.obj \
	swap.obj \
	libew_mt.lib

all: $B\$(APP).exe Tools

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)

Tools: PHONY
	@pushd $@ & \
		echo ---------- & \
		for /f "delims=" %d in ( 'cd' ) do @echo Making $@ in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt & \
	popd


# Clean-up rules
clean:	clean\wave_serverV \
	clean\Tools

clean\wave_serverV: PHONY
	-del a.out core *.o *.obj *% *~

clean\Tools: PHONY
	-@pushd $(@F) & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean & \
	popd

clean_bin: \
	clean_bin\wave_serverV \
	clean_bin\Tools

clean_bin\wave_serverV: PHONY
	-del $B\$(APP) $B\$(APP).exe

clean_bin\Tools: PHONY
	-@pushd $(@F) & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning binaries in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean_bin & \
	popd

PHONY:
