!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)

L = $(EW_HOME)\$(EW_VERSION)\lib

OBJS = \
	ntohl.obj \
	htonl.obj \
	xdr.obj \
	xdr_array.obj \
	xdr_float.obj \
	xdr_stdio.obj

all: $(OBJS)
	copy *.obj $L


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

PHONY:
