.TH "NMXP_CHAN_LIST_NET" 3 "Wed Feb 10 2016" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CHAN_LIST_NET \- Channel list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBnumber\fP"
.br
.ti -1c
.RI "\fBNMXP_CHAN_KEY_NET\fP \fBchannel\fP [\fBMAX_N_CHAN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Channel list\&. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t NMXP_CHAN_LIST_NET::number"

.SS "\fBNMXP_CHAN_KEY_NET\fP NMXP_CHAN_LIST_NET::channel[\fBMAX_N_CHAN\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code\&.
