.TH "NMXP_META_CHAN_LIST" 3 "Wed Feb 10 2016" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_META_CHAN_LIST \- Channel list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBkey\fP"
.br
.ti -1c
.RI "char \fBname\fP [12]"
.br
.ti -1c
.RI "int32_t \fBstart_time\fP"
.br
.ti -1c
.RI "int32_t \fBend_time\fP"
.br
.ti -1c
.RI "char \fBnetwork\fP [12]"
.br
.ti -1c
.RI "struct \fBNMXP_META_CHAN_LIST\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Channel list\&. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t NMXP_META_CHAN_LIST::key"

.SS "char NMXP_META_CHAN_LIST::name[12]"

.SS "int32_t NMXP_META_CHAN_LIST::start_time"

.SS "int32_t NMXP_META_CHAN_LIST::end_time"

.SS "char NMXP_META_CHAN_LIST::network[12]"

.SS "struct \fBNMXP_META_CHAN_LIST\fP* NMXP_META_CHAN_LIST::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code\&.
