.TH "NMXP_CONNECT_REQUEST" 3 "Wed Feb 10 2016" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CONNECT_REQUEST \- Body of ConnectRequest message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBusername\fP [\fBNMXP_MAX_SIZE_USERNAME\fP]"
.br
.ti -1c
.RI "int32_t \fBversion\fP"
.br
.ti -1c
.RI "int32_t \fBconnection_time\fP"
.br
.ti -1c
.RI "int32_t \fBcrc32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Body of ConnectRequest message\&. 
.SH "Member Data Documentation"
.PP 
.SS "char NMXP_CONNECT_REQUEST::username[\fBNMXP_MAX_SIZE_USERNAME\fP]"

.SS "int32_t NMXP_CONNECT_REQUEST::version"

.SS "int32_t NMXP_CONNECT_REQUEST::connection_time"

.SS "int32_t NMXP_CONNECT_REQUEST::crc32"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code\&.
