.TH "NMXP_CHAN_KEY_NET" 3 "Wed Feb 10 2016" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CHAN_KEY_NET \- The key/name info for one channel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBkey\fP"
.br
.ti -1c
.RI "char \fBname\fP [\fBNMXP_CHAN_MAX_SIZE_NAME\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
The key/name info for one channel\&. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t NMXP_CHAN_KEY_NET::key"

.SS "char NMXP_CHAN_KEY_NET::name[\fBNMXP_CHAN_MAX_SIZE_NAME\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code\&.
