.TH "NMXP_CHANNELINFORESPONSE" 3 "Wed Feb 10 2016" "Version 1.2.4" "libnmxp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMXP_CHANNELINFORESPONSE \- Channel info request body\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nmxp_chan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBkey\fP"
.br
.ti -1c
.RI "char \fBname\fP [12]"
.br
.ti -1c
.RI "char \fBnetwork\fP [12]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Channel info request body\&. 
.SH "Member Data Documentation"
.PP 
.SS "int32_t NMXP_CHANNELINFORESPONSE::key"

.SS "char NMXP_CHANNELINFORESPONSE::name[12]"

.SS "char NMXP_CHANNELINFORESPONSE::network[12]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libnmxp from the source code\&.
