!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG=1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) \
		 /DMOD_STR="\"$(APP)\""
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = ewdrift

OBJS = \
	$(APP).obj \
	ewdrift_filt.obj

EW_LIBS = \
	/LIBPATH:$L \
	mem_circ_queue.obj \
	swap.obj \
	trheadconv.obj \
	xfrm.obj \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
