#
# Dummy makefile - only used for cleaning things up
#

B = $(EW_HOME)\$(EW_VERSION)\bin

APP = nll_mgr

$B\$(APP).exe: FAIL


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP)    $B\$(APP).exe
	-del $B\arcfeeder $B\arcfeeder.exe

PHONY:
