LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = nll_mgr

OBJS = $(APP).o

EW_LIBS = \
	$L/chron3.o \
	$L/pipe.o \
	$L/read_arc.o \
	-L$L -lew_mt

all:	$B/nll_mgr \
	$B/arcfeeder

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

$B/arcfeeder: arcfeeder.o
	$(CC) -o $@ $(CFLAGS) arcfeeder.o \
		$L/pipe.o -L$L -lew_mt $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP)    $B/$(APP).exe
	-$(RM) $B/arcfeeder $B/arcfeeder.exe

PHONY:
