#
# Dummy makefile - only used for cleaning things up
#

default: FAIL


# Clean-up rules
clean:	clean/here \
	clean/rpc

clean/here: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean/rpc: PHONY
	-@cd $(@F) && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) -f makefile.unix clean

PHONY:
