!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG=1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = carlstatrig

OBJS = \
	$(APP).obj \
	addtrace.obj \
	cmprscn.obj \
	findsta.obj \
	flushbuf.obj \
	initpars.obj \
	initsta.obj \
	prodstatrg.obj \
	protrace.obj \
	readcnfg.obj \
	readewh.obj \
	readstas.obj \
	resetsta.obj \
	statrpt.obj \
	updtsta.obj

EW_LIBS = \
	/LIBPATH:$L \
	swap.obj \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
