LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lrt -lpthread -lm
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = carlstatrig

OBJS = \
	$(APP).o \
	addtrace.o \
	cmprscn.o \
	findsta.o \
	flushbuf.o \
	initpars.o \
	initsta.o \
	prodstatrg.o \
	protrace.o \
	readcnfg.o \
	readewh.o \
	readstas.o \
	resetsta.o \
	statrpt.o \
	updtsta.o

EW_LIBS = \
	$L/swap.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
