#
# Copyright (c) 2003 Guralp Systems Limited
# Author James McKenzie, contact <software@guralp.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

BINDIR = ${EW_HOME}/${EW_VERSION}/bin
LIBDIR = ${EW_HOME}/${EW_VERSION}/lib

PROG = scream2ew

HSRCS = \
	config.h \
	dispatch.h \
	ewc.h \
	gcf.h \
	gputil.h \
	mainloop.h \
	map.h \
	oscompat.h \
	project.h \
	scream.h \
	util.h

SRCS = \
	main.c \
	config.c \
	dispatch.c \
	ewc.c \
	gcf.c \
	gputil.c \
	mainloop.c \
	map.c \
	scream.c \
	util.c

OBJS = $(SRCS:%.c=%.o)

LOBJS = \
	${LIBDIR}/socket_ew.o \
	${LIBDIR}/swap.o \
	-L${LIBDIR} -lew_mt

${BINDIR}/${PROG}: ${OBJS}
	${CC} -o $@ ${CFLAGS} ${LDFLAGS} ${OBJS} ${LOBJS} ${SPECIFIC_FLAGS}


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) ${BINDIR}/${PROG} ${BINDIR}/${PROG}.exe

checkin: PHONY
	ci -l -m# ${SRCS} ${HSRCS} makefile.sol makefile.nt

tidy: checkin
	indent -i2 -ts0 ${CSRCS} ${HSRCS}

# dependencies

config.o:	project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
dispatch.o:	project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
ewc.o:		project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
gcf.o:		project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
gputil.o:	project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
main.o:		project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
mainloop.o:	project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
map.o:		project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
scream.o:	project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h
util.o:		project.h config.h dispatch.h ewc.h gcf.h gputil.h \
		mainloop.h map.h oscompat.h scream.h util.h

PHONY:
