LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

FilterPickerDir = picker

APP = pick_FP

OBJS = \
	$(APP).o \
	call_FilterPicker.o \
	compare.o \
	config.o \
	index.o \
	initvar.o \
	report.o \
	restart.o \
	stalist.o \
	sniff_eew.o \
	$(FilterPickerDir)/FilterPicker5.o \
	$(FilterPickerDir)/FilterPicker5_Memory.o \
	$(FilterPickerDir)/PickData.o

EW_LIBS = \
	$L/swap.o \
	$L/trheadconv.o \
	-L$L -lew_mt

all: FilterPicker $B/$(APP)

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

FilterPicker: PHONY
	@cd $(FilterPickerDir) && \
		echo Making $@ in: `pwd` ; \
		$(MAKE) -f makefile.unix


# Clean-up rules
clean:	clean/here \
	clean/FilterPicker

clean/here: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean/FilterPicker: PHONY
	-@cd $(FilterPickerDir) && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) -f makefile.unix clean

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
