!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

# -D_NTSDK added to enable definition of getpid() as _getpid() LDD.
CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) /D_NTSDK /DDEBUG
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

OBJS = \
	k2ewmain.obj \
	error_ew_nt.obj \
	getconfig.obj \
	heartbt.obj \
	k2cirbuf.obj \
	k2crctbl.obj \
	k2ewerrs.obj \
	k2ewrstrt.obj \
	k2info.obj \
	k2misc.obj \
	k2pktio.obj \
	k2pktman.obj \
	outptthrd.obj \
	terminat.obj

TCP_OBJS =  k2c_tcp.obj

COM_OBJS = k2c_ser_nt.obj

EW_LIBS = /LIBPATH:$L libew_mt.lib

EW_SOCK_LIBS = \
	/LIBPATH:$L \
	$L\socket_ew.obj \
	$L\socket_ew_common.obj

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

all: $B\k2ew_tcp.exe $B\k2ew_com.exe

$B\k2ew_tcp.exe: $(OBJS) $(TCP_OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(TCP_OBJS) \
		$(EW_SOCK_LIBS) $(EW_LIBS)

$B\k2ew_com.exe: $(OBJS) $(COM_OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(COM_OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\k2ew_tcp $B\k2ew_tcp.exe
	-del $B\k2ew_com $B\k2ew_com.exe

PHONY:
