#
# Dummy makefile - only used for cleaning things up
#

B = $(EW_HOME)/$(EW_VERSION)/bin

APP = startstop

$B/$(APP): FAIL


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
