!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) /DHAS_POLL
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = moleserv

OBJS = \
	$(APP).obj \
	iriswebreq.obj \
	mongoose.obj \
	websrequest.obj

EW_LIBS = \
	/LIBPATH:$L \
	fleng.obj \
	read_arc.obj \
	rw_mag.obj \
	socket_ew.obj \
	socket_ew_common.obj \
	swap.obj \
	ws_clientII.obj \
	libew_mt.lib

ODBC_LIB = odbc32.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS) $(ODBC_LIB)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
