#
# Dummy makefile - only used for cleaning things up
#

B = $(EW_HOME)\$(EW_VERSION)\bin

APP = q2ew

$B\$(APP).exe: FAIL


# Clean-up rules
clean:	clean\here \
	clean\comserv

clean\here: PHONY
	-del a.out core *.o *.obj *% *~

clean\comserv: PHONY
	-@pushd comserv & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean & \
	popd

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
