LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -I$(QLIB_DIR) -Icomserv/include

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

#IGD 2006/11/16 Moved qlib2 to libsrc
QLIB_DIR = $(EW_HOME)/$(EW_VERSION)/src/libsrc/qlib2

APP = q2ew

OBJS = \
	main.o \
	convert.o \
	cs_status.o \
	die.o \
	getconfig.o \
	heart.o \
	logo.o \
	misc_seed_utils.o \
	options.o \
	scn_map.o

COMSERV_LIB = -Lcomserv/util -lutil

QLIB_LIB = -L$(QLIB_DIR)/lib_ew -lqlib2nl

EW_LIBS = -L$L -lew_mt

# IGD 2006/11/16 Note that we use qlib2nl: no-leap-seconds version of Qlib2
$B/q2ew: $(OBJS) comserv/util/libutil.a
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(COMSERV_LIB) $(QLIB_LIB) \
		$(EW_LIBS) $(SPECIFIC_FLAGS)

comserv/util/libutil.a:
	@cd comserv && \
		echo ---------- ; \
		echo Making $@ in: `pwd` ; \
		$(MAKE) -f makefile.unix


# Clean-up rules
clean:	clean/here \
	clean/comserv

clean/here: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean/comserv: PHONY
	-@cd comserv && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) -f makefile.unix clean

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
