!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) /DWIN32
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

U = $(EW_HOME)\$(EW_VERSION)\src\libsrc\util
W = $(EW_HOME)\$(EW_VERSION)\src\libsrc\winnt

APP = SaraAdSend

OBJS = \
	$(APP).obj \
	getconfig.obj \
	SaraUtils.obj

EW_LIBS = /LIBPATH:$L libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
