!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS= $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) /DWIN32

LIB = libpsnms.lib

OBJS =	\
	genutils.obj \
	msrutils.obj \
	pack.obj \
	packdata.obj \
	unpack.obj \
	unpackdata.obj

$(LIB): $(OBJS)
	lib /nologo /out:$@  $(OBJS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~
	-del libpsnms.a libpsnms.lib

PHONY:
