!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP1 = pau
APP2 = pidpau

OBJS = setflags.obj

EW_LIBS = \
	/LIBPATH:$L \
	dirops_ew.obj \
	libew_mt.lib

all: $B\$(APP1).exe $B\$(APP2).exe

$B\$(APP1).exe \
$B\$(APP2).exe: $(@B).obj $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(@B).obj $(OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP1) $B\$(APP1).exe
	-del $B\$(APP2) $B\$(APP2).exe

PHONY:
