LINUX_FLAGS    = -lm -ldl -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = gmewhtmlemail

OBJS = \
	$(APP).o \
	kml_event.o

EW_LIBS = \
	$L/butterworth.o \
	$L/complex_math.o \
	$L/convertInstResponse.o \
	$L/earthworm_defs.o \
	$L/fleng.o \
	$L/geo_to_km.o \
	$L/ioc_filter.o \
	$L/read_arc.o \
	$L/residue.o \
	$L/rw_mag.o \
	$L/rw_strongmotionII.o \
	$L/site.o \
	$L/socket_ew.o \
	$L/socket_ew_common.o \
	$L/sqlite3.o \
	$L/swap.o \
	$L/transferFunction.o \
	$L/watchdog_client.o \
	$L/ws_clientII.o \
	-L$L -lgd -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
