!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt) $(GLOBALFLAGS)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = gmewhtmlemail

OBJS = \
	$(APP).obj \
	kml_event.obj

EW_LIBS = \
	/LIBPATH:$L \
	butterworth.obj \
	complex_math.obj \
	convertInstResponse.obj \
	earthworm_defs.obj \
	fleng.obj \
	geo_to_km.obj \
	ioc_filter.obj \
	read_arc.obj \
	residue.obj \
	rw_mag.obj \
	rw_strongmotionII.obj \
	site.obj \
	socket_ew.obj \
	socket_ew_common.obj \
	sqlite3.obj \
	swap.obj \
	transferFunction.obj \
	watchdog_client.obj \
	ws_clientII.obj \
	libgd.lib \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) -out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
