# note that loc_wcatwc is only geared to run in real time, so to allow
# old picks to be used set the _ALLOW_TANKPLAYBACK flag on for compilation

!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) \
		/D_ADD_TRACE2_HEADER_ /D_ALLOW_TANKPLAYBACK
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = loc_wcatwc

OBJS = \
	$(APP).obj \
	config.obj \
	locate.obj

EB_LIBS = \
	/LIBPATH:$L \
	libebpick.lib \
	libebloc.lib \
	Gdi32.lib \
	WinMM.lib

EW_LIBS = \
	/LIBPATH:$L \
	complex_math.obj \
	swap.obj \
	trheadconv.obj \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EB_LIBS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
