# note that loc_wcatwc is only geared to run in real time, so to allow
# old picks to be used set the _ALLOW_TANKPLAYBACK flag on for compilation

LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -D_ADD_TRACE2_HEADER_ -D_ALLOW_TANKPLAYBACK

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = loc_wcatwc

OBJS = \
	$(APP).o \
	config.o \
	locate.o

EB_LIBS = -L$L -lebpick -lebloc

EW_LIBS = \
	$L/complex_math.o \
	$L/swap.o \
	$L/trheadconv.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EB_LIBS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
