C--THIS FILE IS INCLUDED BY THE FILE 'common.' WHICH IS INCLUDED BY MOST
C  HYPOINVERSE SUBROUTINES
C--SHORT INTEGER DECLARATIONS FOR HYPOINVERSE. *4 VARIABLES ARE OK, JUST LONGER
C--GENERAL PARAMETERS
      INTEGER*2 IRES, IPADD
C--DATA FOR ALL AVAILABLE STATIONS STORED AS LOOKUP TABLE (SUBSCRIPT J)
      INTEGER*2 JFCOR,JXCOR,JPER,JTYPE,JFGWT
      INTEGER*2 JPSWT,JXWT,JFWT,JLATD,JLATM,JLOND,JLONM,JCAL,JPD
      LOGICAL*2 JLMOD,JFM1,JFM2,JXM1,JXM2,JPM1,JPM2
C  CONDENSED TRAVEL TIMES TO 28 DEPTH & 42 DISTANCE POINTS.
      INTEGER*2 KT,KDHR
C--DATA PRESENT FOR EACH STATION REPORTING AN EVENT (SUBSCRIPT K)
      INTEGER*2 KXWT,KFWT,KINDX,KP,KS,KWT,KPER,KCAL,KPAWT
      INTEGER*2 KLSHA,KXMAG,KFMAG,KPMAG,KAMPU,KAMPTYP,KIMTYP
C--DATA PRESENT FOR EACH PHASE (P OR S) REPORTED FOR THIS EVENT (SUBSCRIPT IM)
      INTEGER*2 IND,IMPORT,MTCAL
      LOGICAL*2 MSFLAG
C--TRAVEL TIMES ARE STORED IN INTEGER*2 ARRAYS IN TT UNITS OF 0.01 SECS
C--TTMIN AND TTMAX ARE THE MINIMUM AND MAXIMUM VALID TT TRAVEL TIMES
C--TTUNDR AND TTOVER ARE USED TO FLAG TT TRAVEL TIME UNDERFLOW OR OVERFLOW
C--TTUNDF IS USED TO FLAG UNDEFINED TT TRAVEL TIMES
C--TTUNDR < TTMIN < VALID_TT < TTMAX < TTOVER
C--TTUNDF < TTUNDR OR TTUNDF > TTOVER
      INTEGER*2  TTMIN, TTMAX, TTUNDR, TTOVER, TTUNDF
      PARAMETER ( TTMIN  = -32766 )
      PARAMETER ( TTMAX  =  32766 )
      PARAMETER ( TTUNDR = -32767 )
      PARAMETER ( TTOVER =  32767 )
      PARAMETER ( TTUNDF = -32768 )
