!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = StartstopPipeConsole

OBJS = $(APP).obj

EW_LIBS = \
	/LIBPATH:$L \
	ew_nevent_message.obj \
	lockfile.obj \
	lockfile_ew.obj \
	pipeconsole.obj \
	service_ew.obj \
	startstop_lib.obj \
	startstop_winlib.obj \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)
	mt.exe /nologo /manifest "$(APP).exe.manifest" /outputresource:"$B\$(APP).exe"
# (using 'mt.exe' to add manifest so program requests Administrator level)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
