!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

# added -D_NTSDK to enable definition of getpid() as _getpid() LDD.
CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS) /I$(LS) /D_NTSDK
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib
LS = libslink

APP = slink2ew

OBJS = $(APP).obj

EW_LIBS = \
	/LIBPATH:$L \
	mem_circ_queue.obj \
	parse_ip_address.obj \
	socket_ew.obj \
	socket_ew_common.obj \
	swap.obj \
	libslink.lib libmseed.lib libew_mt.lib

$B\$(APP).exe: $(OBJS) $L\libslink.lib
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)

$L\libslink.lib:
	@pushd $(LS) & \
		echo ---------- & \
		for /f "delims=" %d in ( 'cd' ) do @echo Making $(@F) in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt & \
	popd


# Clean-up rules
clean:	clean\here \
	clean\libslink

clean\here: PHONY
	-del a.out core *.o *.obj *% *~

clean\libslink: PHONY
	-@pushd $(LS) & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean & \
	popd

clean_bin: \
	clean_bin\here \
	clean_bin\libslink

clean_bin\here: PHONY
	-del $B\$(APP) $B\$(APP).exe

clean_bin\libslink: PHONY
	-@pushd $(LS) & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning binaries in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean_bin & \
	popd

PHONY:
