LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -I$(LS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib
LS = libslink

APP = slink2ew

OBJS = $(APP).o

EW_LIBS = \
	$L/mem_circ_queue.o \
	$L/parse_ip_address.o \
	$L/socket_ew.o \
	$L/socket_ew_common.o \
	$L/swap.o \
	-L$L -lslink -lmseed -lew_mt

$B/$(APP): $(OBJS) $L/libslink.a
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

$L/libslink.a:
	@cd $(LS) && \
		echo ---------- ; \
		echo Making $(@F) in: `pwd` ; \
		$(MAKE) static
	mv $(LS)/libslink.a $L/


# Clean-up rules
clean:	clean/here \
	clean/libslink

clean/here: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean/libslink: PHONY
	-@cd $(LS) && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) clean
	-$(RM) $L/libslink.a

clean_bin: \
	clean_bin/here \
	clean_bin/libslink

clean_bin/here: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

clean_bin/libslink: PHONY
	-$(RM) $B/libslink.dll

PHONY:
