LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS    = $(GLOBALFLAGS) -I$(QLIB_DIR) -DNO_LEAPSECONDS -DSUPPORT_SCNL
SCN_FLAGS = $(GLOBALFLAGS) -I$(QLIB_DIR) -DNO_LEAPSECONDS

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

QLIB_DIR = $(EW_HOME)/$(EW_VERSION)/src/libsrc/qlib2

OBJ = \
	ew2mseed.o \
	ew2mseed_config.o \
	ew2mseed_files.o \
	ew2mseed_log.o \
	ew2mseed_swap.o \
	ew2mseed_utils.o \
	isti_ws_client.o \
	ws_requests.o \
	$L/ws_clientII.o

OBJ_NL = \
	ew2mseed_config_nl.o \
	ew2mseed_files_nl.o \
	ew2mseed_log_nl.o \
	ew2mseed_nl.o \
	ew2mseed_swap_nl.o \
	ew2mseed_utils_nl.o \
	isti_ws_client_nl.o \
	ws_requests_nl.o \
	$L/ws_clientII_no_location.o

QLIB_LIB = -L$(QLIB_DIR)/lib_ew -lqlib2nl

EW_LIBS = \
	$L/socket_ew.o \
	$L/swap.o \
	$L/socket_ew_common.o \
	-L$L -lew_mt

OBJS = wsSniffer.o

all:	$B/ew2mseed \
	$B/ew2mseed_nl

$B/ew2mseed: $(OBJ)
	$(CC) -o $@ $(CFLAGS) $(OBJ) $(QLIB_LIB) $(EW_LIBS) $(SPECIFIC_FLAGS)

$B/ew2mseed_nl: $(OBJ_NL)
	$(CC) -o $@ $(CFLAGS) $(OBJ_NL) $(QLIB_LIB) $(EW_LIBS) $(SPECIFIC_FLAGS)

$B/wsSniffer: $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)
	
ew2mseed_nl.o: ew2mseed.c
	$(CC) -c -o $@ $(SCN_FLAGS) ew2mseed.c

ew2mseed_config_nl.o: ew2mseed_config.c
	$(CC) -c -o $@ $(SCN_FLAGS) ew2mseed_config.c

ew2mseed_log_nl.o: ew2mseed_log.c
	$(CC) -c -o $@ $(SCN_FLAGS) ew2mseed_log.c

ew2mseed_files_nl.o: ew2mseed_files.c
	$(CC) -c -o $@ $(SCN_FLAGS) ew2mseed_files.c

ew2mseed_swap_nl.o: ew2mseed_swap.c
	$(CC) -c -o $@ $(SCN_FLAGS) ew2mseed_swap.c

ew2mseed_utils_nl.o: ew2mseed_utils.c
	$(CC) -c -o $@ $(SCN_FLAGS) ew2mseed_utils.c

ws_requests_nl.o: ws_requests.c
	$(CC) -c -o $@ $(SCN_FLAGS) ws_requests.c

isti_ws_client_nl.o: isti_ws_client.c
	$(CC) -c -o $@ $(SCN_FLAGS) isti_ws_client.c


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/ew2mseed    $B/ew2mseed.exe
	-$(RM) $B/ew2mseed_nl $B/ew2mseed_nl.exe
	-$(RM) $B/wsSniffer   $B/wsSniffer.exe

PHONY:
