!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = waveman2disk

OBJS = \
	$(APP).obj \
	CatPsuedoTrig.obj

EW_LIBS = \
	/LIBPATH:$L \
	ahputaway.obj \
	cosmos0putaway.obj \
	dirops_ew.obj \
	geo_to_km.obj \
	gseputaway.obj \
	htonl.obj \
	mem_circ_queue.obj \
	mseedputaway.obj \
	ntohl.obj \
	parse_trig.obj \
	psn4putaway.obj \
	putaway.obj \
	read_arc.obj \
	sacputaway.obj \
	seiputaway.obj \
	seiutils.obj \
	socket_ew.obj \
	socket_ew_common.obj \
	sudsputaway.obj \
	swap.obj \
	tankputaway.obj \
	ws_clientII.obj \
	xdr.obj \
	xdr_stdio.obj \
	xdr_float.obj \
	xdr_array.obj \
	libmseed.lib \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
