!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin

APP = Hypo71PC

SRCS = \
	main.f \
	hypo1m2.f \
	hypo2.f \
	hypo3.f \
	hypo4.f \
	single.f \
	ytrv.f \
	input1.f \
	timz3.f \
	geo_sp.f

$B\$(APP).exe: $(SRCS)
	$(FC) /exe:$@ $(FFLAGS) $(LDFLAGS) $(SRCS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe
	-rmdir /S /Q $B\$(APP).dSYM

PHONY:
