################################################################################
# Copyright (c) 2017, Guralp Systems Limited. All rights reserved.
#
# The following are the licensing terms and conditions (the “License Agreement”)
# under which Guralp Systems Limited (“GSL”) grants access to, use of and
# redistribution of the “Code” (as defined below) to a recipient (the “Licensee”).
# Any use or redistribution of the Code by the Licensee shall be deemed to be
# acceptance of the terms and conditions of this License Agreement. In the event
# of inconsistency or conflict between this License Agreement and any other
# license for the Code then the terms of this License Agreement shall prevail.
#
# The Code is defined as each and every file in any previous or current
# distribution of the source-code and compiled executables comprising the gdi2ew
# distributable (inclusive of all supporting and embedded documentation) and
# subsequent releases thereof as may be made available by GSL from time to time.
#
# 1. The License. GSL grants to the Licensee (and Sub-Licensee if applicable)
# a non-exclusive perpetual (subject to termination by GSL in accordance with
# paragraph 4) license (the “License”) to use (“Use”) the Code either alone or
# in conjunction with other code to produce one or more applications (each a
# Derived Product) and/or redistribute the Code or Derived Product
# (Redistribution”) to a third party (each being a “Sub-Licensee”), in each case
# strictly in accordance with the terms and conditions of this License Agreement.
#
# 2. Redistribution Conditions. Redistribution and Use of the Code, with or
# without modification, is permitted under the terms of this License Agreement
# provided that the following conditions are met by the Licensee and any Sub
# Licensee:
#
# a) Redistribution of the Code must include within the documentation and/or
# other materials provided with the Redistribution the copyright notice
# “Copyright ©2017, Guralp Systems Limited. All rights reserved”.
#
# b) The Licensee and any Sub-Licensee is responsible for ensuring that any
# party to whom the Code is redistributed is bound by the terms of this License
# as a “Sub-Licensee” and will therefore make Use of the Code on the basis of
# understanding and accepting this Licence Agreement.
#
# c) Neither the name of Guralp Systems, nor the Guralp logo, nor the names of
# GSL’s contributors may be used to endorse or promote products derived from the
# Code without specific prior written permission from GSL.
#
# d) Neither the Licensee nor any Sub-Licensee may charge any form of fee or
# royalty for providing the Code to a third party other than as embedded as a
# proportionate element of the fee or royalty charged for a Derived Product.
#
# e) A Licensee or Sub-licensee may charge a fee or royalty for a Derived
# Product.
#
# 3. DISCLAIMER. EXCEPT AS EXPRESSLY PROVIDED IN THIS LICENSE, GSL HEREBY
# EXCLUDES ANY IMPLIED CONDITION OR WARRANTY CONCERNING THE MERCHANTABILITY OR
# QUALITY OR FITNESS FOR PURPOSE OF THE CODE, WHETHER SUCH CONDITION OR WARRANTY
# IS IMPLIED BY STATUTE OR COMMON LAW. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLAR
# , OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS CODE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# 4. Term and Termination. This License Agreement shall commence on acceptance
# of these terms by the Licensee (or Sub-Licensee as applicable) and shall
# continue unless terminated by GSL for cause in the event that the Licensee (or
# Sub-Licensee as applicable) commits any material breach of this License
# Agreement and fails to remedy that breach within 30 days of being given
# written notice of that breach by GSL.
#
# 5. Law and Jurisdiction. This License Agreement is governed by the laws of
# England and Wales, and is subject to the exclusive jurisdictions of the
# English courts.
################################################################################

LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -DLINUX

BINDIR = ${EW_HOME}/${EW_VERSION}/bin
LIBDIR = ${EW_HOME}/${EW_VERSION}/lib

PROG = gdi2ew

HSRCS = \
	config.h \
	ewc.h \
	gdi.h \
	gdi_client.h \
	gdi_commands.h \
	gdi_comms.h \
	gdi_server.h \
	gdi_thread.h \
	oscompat.h \
	project.h \
	util.h \
	vint.h

SRCS = \
	main.c \
	config.c \
	ewc.c \
	gdi.c \
	gdi_client.c \
	gdi_comms.c \
	gdi_commands.c \
	gdi_server.c \
	gdi_thread.c \
	util.c \
	vint.c

OBJS = $(SRCS:%.c=%.o)

LOBJS = \
	${LIBDIR}/socket_ew.o \
	${LIBDIR}/socket_ew_common.o \
	${LIBDIR}/swap.o \
	-L${LIBDIR} -lew_mt

${BINDIR}/${PROG}: ${OBJS}
	${CC} -o $@ ${CFLAGS} ${LDFLAGS} ${OBJS} ${LOBJS} ${SPECIFIC_FLAGS}


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) ${BINDIR}/${PROG} ${BINDIR}/${PROG}.exe

checkin: PHONY
	ci -l -m# ${SRCS} ${HSRCS} makefile.sol makefile.nt

tidy: checkin
	indent -i2 -ts0 ${CSRCS} ${HSRCS}

# Dependencies

config.o:	project.h config.h ewc.h oscompat.h util.h
ewc.o:		project.h config.h ewc.h oscompat.h util.h
main.o:		project.h config.h ewc.h oscompat.h util.h
util.o:		project.h config.h ewc.h oscompat.h util.h
gdi_client.o:	project.h gdi.h
gdi.o:		project.h gdi_defs.h gdi_server.h gdi_comms.h gdi_thread.h
gdi_server.o:	project.h

PHONY:
