#
# Dummy makefile - only used for cleaning things up
#

B = $(EW_HOME)/$(EW_VERSION)/bin

default: FAIL


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/mGetMenu.dll $B/mGetBinary.dll $B/mGetAscii.dll

PHONY:
