!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

LIB = libslink

OBJS = \
	config.obj \
	genutils.obj \
	globmatch.obj \
	gswap.obj \
	logging.obj \
	msrecord.obj \
	network.obj \
	slplatform.obj \
	slutils.obj \
	statefile.obj \
	strutils.obj \
	unpack.obj

all: $L\$(LIB).lib

$L\$(LIB).lib: $(OBJS)
	lib /nologo /out:$@ $(OBJS)

$B\$(LIB).dll: $(OBJS)
	$(link) /dll /nologo /out:$@ $(OBJS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~
	-del $L\$(LIB).lib

clean_bin: PHONY
	-del $B\$(LIB).dll

PHONY:
