LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -DSROS_LINUX

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

SR_HOME = $(EW_HOME)/$(EW_VERSION)/src/data_sources/sr2ew

APP = sr2ew

OBJS = \
	$(APP).o \
	CustomPipeLib.o

EW_LIBS = \
	$L/getutil.o \
	$L/kom.o \
	$L/logit_mt.o \
	$L/sleep_ew.o \
	$L/time_ew.o \
	$L/transport.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
