; FILE: Sr2Ew.ini
; COPYRIGHT: (c), Symmetric Research, 2009-2016
;
; Sample ini file for Sr2EwPipeline.bat initialization.  Acquire data
; from a USBxCH and send it to an Earthworm system.
;
; Each of the following [xxx] sections set the parameters for that particular
; pipeline stage comprising sr2ew
;
; For details on the various parameters see the .ini files for each respective
; pipeline utility.
;
; Edit these parameters as appropriate for your application.  See
; Sr2EwPipeline.bat for the layout of the pipeline itself.
;
;


; Required SR_USBUXCH_Ini header line: *** DO NOT REMOVE OR CHANGE ***

SR_USBXCH_Ini


[Blast]

        ; Blast parameters for primary acqusition:

        ; Blast parameters for primary acqusition:

        DriverName = "SrUsbXch0" ; identifies A/D board
        SampleRate = "s6"        ; 130 Hz, "Blast /i" for all rates
        GpsName = "g2"           ; timing from g1 -> PC time, g2 -> Garmin GPS
        PakFileSize = "Big"      ; save PAK files with about 10 minutes of data


[Pak2Bin]

        ; Pak2Bin parameters for converting Blast PAK data to BIN format:


        Verbose = 0             ; amount of working output, 0 -> none, 4 -> lots
        MsgCount = 0            ; progress message after this many packets


[Interp]

        ; Interp parameters for interpolating down to lower sampling rate:

        OutputRate = 100        ; output sampling rate in Hz
        MsgCount = 0            ; progress message after this many samples


; [sr2ew] parameters are set from sr2ew.d, an Earthworm style config file.

[Bin2Asc]

        ; Bin2Asc parameters for converting Pak2Bin BIN format to ASCII:

        OutputFormat = "fw8"         ; scaled fixed width, 8 channel
        OutputPrefix = "SREW-"       ; user selected name
        DataFileMode = "Sequential"  ; start new file when current has MaxLines
        MaxLines     = 10000         ; number data rows per file

        Title0 = "Chan 0"           ; make analog channel titles match scope display
        Title1 = "Chan 1"
        Title2 = "Chan 2"
        Title3 = "Chan 3"
        Title4 = "Chan 4"
        Title5 = "Chan 5"
        Title6 = "Chan 6"
        Title7 = "Chan 7"

       ; use default places and digits values suitable for display as counts


[Calibrate]  

        ; Use default calibration into counts
