!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP  = ewhtmlemail
TEST = ge_test

OBJS = \
	$(APP).obj \
	kml_event.obj

EW_LIBS = \
	/LIBPATH:$L \
	butterworth.obj \
	complex_math.obj \
	convertInstResponse.obj \
	decode.obj \
	earthworm_defs.obj \
	encode.obj \
	fleng.obj \
	geo_to_km.obj \
	geom.obj \
	ioc_filter.obj \
	read_arc.obj \
	residue.obj \
	rw_mag.obj \
	site.obj \
	socket_ew.obj \
	socket_ew_common.obj \
	swap.obj \
	transferFunction.obj \
	watchdog_client.obj \
	ws_clientII.obj \
	libcrypto.lib \
	libgd.lib \
	libew_mt.lib

TEST_LIBS = \
	/LIBPATH:$L \
	decode.obj \
	encode.obj \
	libcrypto.lib

all: $B\$(APP).exe $B\$(TEST).exe

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)

$B\$(TEST).exe: $(TEST).obj
	$(link) /out:$@ $(LDFLAGS) $(TEST).obj $(TEST_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP)  $B\$(APP).exe
	-del $B\$(TEST) $B\$(TEST).exe

PHONY:
