LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = sac2hypo

OBJS = \
	$(APP).o \
	arc_2_ewevent.o \
	init_ewevent.o \
	sac_2_ewevent.o

EW_LIBS = \
	$L/chron3.o \
	$L/dirops_ew.o \
	$L/geo_to_km.o \
	$L/getutil.o \
	$L/kom.o \
	$L/logit_mt.o \
	$L/read_arc.o \
	$L/sacputaway.o \
	$L/sema_ew.o \
	$L/sleep_ew.o \
	$L/socket_ew.o \
	$L/socket_ew_common.o \
	$L/swap.o \
	$L/time_ew.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
