LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = seisan_report

OBJS = $(APP).o

EW_LIBS = \
	$L/copyfile.o \
	$L/dirops_ew.o \
	$L/fleng.o \
	$L/nordic.o \
	$L/read_arc.o \
	$L/rw_mag.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
