LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lc -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = eqfilterII

OBJS = \
	$(APP).o \
	area.o

EW_LIBS = \
	$L/mem_circ_queue.o \
	$L/global_loc_rw.o \
	$L/global_msg.o \
	$L/rayloc_message_rw.o \
	$L/read_arc.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
