# The socket calls to socket_lnx.c are broken on Linux/MacOS: undefined references
# It is not known whether the Solaris or Windows version works

!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin

APP = sendfile_srv

OBJS = \
	$(APP).obj \
	chdir_win.obj \
	config.obj \
	fopen_win.obj \
	getfname_win.obj \
	log.obj \
	sleep_win.obj \
	socket_win.obj \
	tzset_win.obj

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
