LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

# The following lines set the location of the SR USBxCH library
# functions needed to compile srusb2ew.  Un-comment the first line
# below when compiling from the Earthworm directory tree and the
# second when compiling from the SR directory tree.

SR_HOME = $(EW_HOME)/$(EW_VERSION)/src/data_sources/srusb2ew
#SR_HOME = /usr/local/SR

USBXCH = $(SR_HOME)/USBXCH

USBXCHINC = $(USBXCH)/Include
USBXCHLIB = $(USBXCH)/Lib/SrUsbXch.c
HELPERLIB = $(USBXCH)/Lib/SrHelper.c

PDEF    = -DSROS_LINUX
CFLAGSR = $(CFLAGS) -fPIC

APP = srusb2ew

OBJS = \
	$(APP).o \
	SrHelper.o \
	SrUsbXch.o

EW_LIBS = -L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

$(APP).o: $(APP).c
	$(CC) -c $(CFLAGS) $(PDEF) -I$(USBXCHINC) $(APP).c

SrUsbXch.o: $(USBXCHLIB)
	$(CC) -c $(CFLAGSR) $(PDEF) -I$(USBXCHINC) $(USBXCHLIB)

SrHelper.o: $(HELPERLIB)
	$(CC) -c $(CFLAGSR) $(PDEF) -I$(USBXCHINC) $(HELPERLIB)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
