LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) `$(MYSQL_CONFIG_PROG) --cflags`

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = dcsn

MYSQL_CONNECTOR_C_PATH_BUILD = $(EW_HOME)/$(EW_VERSION)/src/archiving/mole/mysql-connector-c-build
# In case of need, change MYSQL_CONNECTOR_C_PATH_BUILD with the appropriate path to 32bit mysql_config executable
# MYSQL_CONNECTOR_C_PATH_BUILD = /usr
# MYSQL_CONNECTOR_C_PATH_BUILD = /opt/local/lib/mysql5
MYSQL_CONFIG_PROG_PATH = $(MYSQL_CONNECTOR_C_PATH_BUILD)/bin
MYSQL_CONFIG_PROG = $(MYSQL_CONFIG_PROG_PATH)/mysql_config

OBJS = $(APP).o

MYSQL_LIB = `$(MYSQL_CONFIG_PROG) --libs_r`

EW_LIBS = \
	$L/getutil.o \
	$L/kom.o \
	$L/lockfile.o \
	$L/lockfile_ew.o \
	$L/logit_mt.o \
	$L/sleep_ew.o \
	$L/time_ew.o \
	$L/transport.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(MYSQL_LIB) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
