LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

FilterPickerDir = picker

APP = pick_FP

OBJS = \
	$(APP).o \
	call_FilterPicker.o \
	compare.o \
	config.o \
	index.o \
	initvar.o \
	report.o \
	restart.o \
	stalist.o \
	FilterPicker5.o \
	FilterPicker5_Memory.o \
	PickData.o

EW_LIBS = \
	$L/swap.o \
	$L/trheadconv.o \
	-L$L -lew_mt

all:	$B/pick_FP \
	FilterPicker	

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

FilterPicker5.o:	$(FilterPickerDir)/FilterPicker5.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $(FilterPickerDir)/FilterPicker5.c

FilterPicker5_Memory.o:	$(FilterPickerDir)/FilterPicker5_Memory.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $(FilterPickerDir)/FilterPicker5_Memory.c

PickData.o:		$(FilterPickerDir)/PickData.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $(FilterPickerDir)/PickData.c

FilterPicker: PHONY
	@cd $(FilterPickerDir) && \
		echo ---------- ; \
		echo Making $@ in: `pwd` ; \
		$(MAKE) -f makefile.unix


# Clean-up rules
clean:	clean/here \
	clean/FilterPicker

clean/here: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean/FilterPicker: PHONY
	-@cd $(FilterPickerDir) && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) -f makefile.unix clean

clean_bin: \
	clean_bin/here \
	clean_bin/FilterPicker

clean_bin/here: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

clean_bin/FilterPicker: PHONY
	-@cd $(FilterPickerDir) && \
		echo Cleaning binaries in: `pwd` ; \
		$(MAKE) -f makefile.unix clean_bin

PHONY:
