LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -DSTDC -I$(GCF_INC)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

GCF_INC = gcf/include

APP = gcf2ew

OBJS = \
	main.o \
	convert.o \
	die.o \
	getconfig.o \
	heart.o \
	logo.o \
	options.o \
	scn_map.o

LINUX_GCF_LIB   = -Lgcf/liblinux32 -lgcf
SOLARIS_GCF_LIB = -Lgcf/lib -lgcf
GCF_LIB = $($(PLATFORM)_GCF_LIB)

EW_LIBS = -L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(GCF_LIB) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
