!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = startstop_service

OBJS = $(APP).obj

EW_LIBS = \
	/LIBPATH:$L \
	ew_nevent_message.obj \
	lockfile.obj \
	lockfile_ew.obj \
	pipeconsole.obj \
	service_ew.obj \
	startstop_lib.obj \
	startstop_winlib.obj \
	libew_mt.lib

all: $B\$(APP).exe StartstopPipeConsole

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)

StartstopPipeConsole: PHONY
	@pushd $@ & \
		echo ---------- & \
		for /f "delims=" %d in ( 'cd' ) do @echo Making $@ in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt & \
	popd


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~
	-@pushd StartstopPipeConsole & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean & \
	popd

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe
	-@pushd StartstopPipeConsole & \
		for /f "delims=" %d in ( 'cd' ) do @echo Cleaning binaries in: %d & \
		$(MAKE) /$(MAKEFLAGS) /f makefile.nt clean_bin & \
	popd

PHONY:
