#
# Dummy makefile - only used for cleaning things up
#

B = $(EW_HOME)/$(EW_VERSION)/bin

APP = startstop_service

$B/$(APP): FAIL


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~
	-@cd StartstopPipeConsole && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) -f makefile.unix clean

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe
	-@cd StartstopPipeConsole && \
		echo Cleaning binaries in: `pwd` ; \
		$(MAKE) -f makefile.unix clean_bin

PHONY:
