LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = trig2disk

OBJS = \
	$(APP).o \
	CatPsuedoTrig.o

EW_LIBS = \
	$L/ahputaway.o \
	$L/cosmos0putaway.o \
	$L/dirops_ew.o \
	$L/geo_to_km.o \
	$L/gseputaway.o \
	$L/mem_circ_queue.o \
	$L/mseedputaway.o \
	$L/parse_trig.o \
	$L/putaway.o \
	$L/read_arc.o \
	$L/sacputaway.o \
	$L/seiputaway.o \
	$L/seiutils.o \
	$L/socket_ew.o \
	$L/socket_ew_common.o \
	$L/sudsputaway.o \
	$L/swap.o \
	$L/tankputaway.o \
	$L/uwputaway.o \
	$L/wfdiscputaway.o \
	$L/ws_clientII.o \
	-L$L -luw -lmseed -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
