LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS   = $(GLOBALFLAGS)
CXXFLAGS = $(CFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib
D = PsnAdBoard

APP = psnadsend

OBJS = \
	PsnAdSend.o \
	PsnAdUtils.o \
	filter.o \
	getconfig.o

AD_LIBS = -LPsnAdBoard -lpsn_ew

EW_LIBS = \
	$L/getutil.o \
	$L/kom.o \
	$L/logit_mt.o \
	$L/sleep_ew.o \
	$L/time_ew.o \
	$L/transport.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS) $D/libpsn_ew.a
	$(CXX) -o $@ $(CXXFLAGS) $(OBJS) $(AD_LIBS) $(EW_LIBS) $(SPECIFIC_FLAGS)

PsnAdSend.o:	PsnAdSend.cpp  PsnAdSend.h
PsnAdUtils.o:	PsnAdUtils.cpp PsnAdSend.h
filter.o:	filter.cpp     PsnAdSend.h
getconfig.o:	getconfig.cpp  PsnAdSend.h

$D/libpsn_ew.a:
	@cd PsnAdBoard && \
		echo ---------- ; \
		echo Making $@ in: `pwd` ; \
		$(MAKE) -f makefile.unix
	

# Clean-up rules
clean:	clean/here \
	clean/lib

clean/here: PHONY
	-$(RM) a.out core *.o *.obj *.a *% *~

clean/lib: PHONY
	-@cd PsnAdBoard && \
		echo Cleaning in: `pwd` ; \
		$(MAKE) -f makefile.unix clean

clean_bin: \
	clean_bin/here \
	clean_bin/lib

clean_bin/here: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

clean_bin/lib: PHONY
	-@cd PsnAdBoard && \
		echo Cleaning binaries in: `pwd` ; \
		$(MAKE) -f makefile.unix clean_bin

PHONY:
