LINUX_FLAGS    = -lpthread
SOLARIS_FLAGS  = -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -I$(EW_HOME)/$(EW_VERSION)/src/libsrc/libdali

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = ewexport2ringserver

OBJS = \
	$(APP).o \
	network.o \
	util.o

EW_LIBS = -L$L -ldali -lmseed

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP)*.exe

PHONY:
