!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

EW_LIBS = \
	/LIBPATH:$L \
	pipe.obj \
	libew_mt.lib

all:	$B\eqverify_assemble.exe \
	$B\arcfeeder.exe

$B\eqverify_assemble.exe: eqverify_assemble.obj
	$(link) /out:$@ $(LDFLAGS) eqverify_assemble.obj $(EW_LIBS)

$B\arcfeeder.exe: arcfeeder.obj
	$(link) /out:$@ $(LDFLAGS) arcfeeder.obj $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\eqverify_assemble $B\eqverify_assemble.exe
	-del $B\arcfeeder         $B\arcfeeder.exe

PHONY:
