!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG=1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = eqcoda

OBJS = \
	$(APP).obj \
	eqm2_calls.obj \
	stalist.obj

EW_LIBS = \
	/LIBPATH:$L \
	pipe.obj \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)

$B\feedeqcoda.exe: feedeqcoda.obj
	$(link) /out:$@ $(LDFLAGS) feedeqcoda.obj $(EW_LIBS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP)     $B\$(APP).exe
	-del $B\feedeqcoda $B\feedeqcoda.exe

PHONY:
