LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = eqcoda

OBJS = \
	$(APP).o \
	eqm2_calls.o \
	stalist.o

EW_LIBS = \
	$L/pipe.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

$B/feedeqcoda: feedeqcoda.o
	$(CC) -o $@ feedeqcoda.o $(EW_LIBS) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP)     $B/$(APP).exe
	-$(RM) $B/feedeqcoda $B/feedeqcoda.exe

PHONY:
