!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)

L = $(EW_HOME)\$(EW_VERSION)\lib
I = $(EW_HOME)\$(EW_VERSION)\include

LIB = libmseed.lib
DLL = libmseed.dll

OBJS = \
	fileutils.obj \
	genutils.obj \
	gswap.obj \
	lmplatform.obj \
	logging.obj \
	lookup.obj \
	msrutils.obj \
	pack.obj \
	packdata.obj \
	parseutils.obj \
	selection.obj \
	traceutils.obj \
	tracelist.obj \
	unpack.obj \
	unpackdata.obj

all: $L\$(LIB) install

$L\$(LIB): $(OBJS)
	lib /nologo /out:$@ $(OBJS)

$L\$(DLL): $(OBJS)
	$(link) /dll /nologo /out:$@ $(OBJS)

install: PHONY
	copy libmseed.h   $I
	copy lmplatform.h $I


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~
	-del $L\libmseed.a $L\libmseed.lib
	-del $I\libmseed.h $I\lmplatform.h

PHONY:
