LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -O

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib

APP = fir

OBJS = \
	$(APP).o \
	bandcom.o \
	configure.o \
	filt1scn.o \
	firfilt.o \
	firthrd.o \
	hqr.o \
	initpars.o \
	initsta.o \
	matchscn.o \
	readcnfg.o \
	readewh.o \
	remeznp.o \
	resetsta.o \
	setfilt.o \
	statrpt.o \
	zeroes.o

EW_LIBS = \
	$L/mem_circ_queue.o \
	$L/swap.o \
	-L$L -lew_mt

$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(SPECIFIC_FLAGS)

hqr.o: ../decimate/hqr.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) ../decimate/hqr.c


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
