!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG=1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)
LDFLAGS = $(conlflags) $(ldebug) $(conlibsmt)

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib

APP = fir

OBJS = \
	$(APP).obj \
	bandcom.obj \
	configure.obj \
	filt1scn.obj \
	firfilt.obj \
	firthrd.obj \
	hqr.obj \
	initpars.obj \
	initsta.obj \
	matchscn.obj \
	readcnfg.obj \
	readewh.obj \
	remeznp.obj \
	resetsta.obj \
	setfilt.obj \
	statrpt.obj \
	zeroes.obj

EW_LIBS = \
	/LIBPATH:$L \
	mem_circ_queue.obj \
	swap.obj \
	libew_mt.lib

$B\$(APP).exe: $(OBJS)
	$(link) /out:$@ $(LDFLAGS) $(OBJS) $(EW_LIBS)

hqr.obj: ..\decimate\hqr.c
	$(CC) $(CFLAGS) ..\decimate\hqr.c


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~

clean_bin: PHONY
	-del $B\$(APP) $B\$(APP).exe

PHONY:
