LINUX_FLAGS    = -lm -lpthread
SOLARIS_FLAGS  = -lm -lnsl -lsocket -lrt -lpthread
SPECIFIC_FLAGS = $($(PLATFORM)_FLAGS)

CFLAGS = $(GLOBALFLAGS) -I$(QLIB_DIR)

B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib
QLIB_DIR = $(EW_HOME)/$(EW_VERSION)/src/libsrc/qlib2

APP = nq2gif

OBJS = main.o

EW_LIBS = \
	$L/dirops_ew.o \
	-L$L -lgd -lew_mt

QLIB_LIB = $(QLIB_DIR)/lib_ew/libqlib2nl.a

# IGD 2006/11/16 Note that we use qlib2nl: no-leap-seconds version of Qlib2
$B/$(APP): $(OBJS)
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(EW_LIBS) $(QLIB_LIB) $(SPECIFIC_FLAGS)


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~

clean_bin: PHONY
	-$(RM) $B/$(APP) $B/$(APP).exe

PHONY:
